artifact_location: file:///workspaces/augmented_data_plot_price_pred/mlops_pipeline/mlflow_runs/0
creation_time: 1749568904570
experiment_id: '0'
last_update_time: 1749568904570
lifecycle_stage: active
name: Default
