artifact_location: file:///workspaces/augmented_data_plot_price_pred/mlops_pipeline/mlflow_runs/987692625265231840
creation_time: 1749568904578
experiment_id: '987692625265231840'
last_update_time: 1749568904578
lifecycle_stage: active
name: Plot Price Prediction - V2
